version: '3'
services: 
    front:
        container_name: front
        build: ./front
    back:
        container_name: back
        build: ./back
    nginx:
        container_name: nginx
        image: nginx:latest
        ports:
            - 80:80
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - front
            - back