name: deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Prepare for deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
            eval $(ssh-agent -s)
            echo "${{ secrets.SSH_PRIVATE_KEY }}" | ssh-add -
            mkdir -p ~/.ssh
            echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
      - name: Deliver static
        run: |
          scp -r ./front neironk@neiron.solutions:~/test
          scp -r ./back neironk@neiron.solutions:~/test
          scp ./docker-compose ./nginx.conf neironk@neiron.solutions:~/test