name: deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Prepare for deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
            which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )
            eval $(ssh-agent -s)
            mkdir -p ~/.ssh
            chmod 700 ~/.ssh
            echo "$SSH_PRIVATE_KEY" > ~/.ssh/key
            chmod 600 ~/.ssh/key
            ssh-keyscan neiron.solutions >> ~/.ssh/known_hosts
            chmod 644 ~/.ssh/known_hosts
            scp -i ~/.ssh/key -r ./front neironk@neiron.solutions:~/test
            scp -i ~/.ssh/key -r ./back neironk@neiron.solutions:~/test
            scp -i ~/.ssh/key ./docker-compose.yml ./nginx.conf neironk@neiron.solutions:~/test