name: deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Deliver static
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
            eval $(ssh-agent -s)
            echo "${{ secrets.SSH_PRIVATE_KEY }}" | ssh-add -
            mkdir -p ~/.ssh
            echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
            scp -r ./front neironk@neiron.solutions:~/msc
            scp -r ./back neironk@neiron.solutions:~/msc
            scp ./docker-compose.yml ./nginx.conf neironk@neiron.solutions:~/msc
      - name: Restart container
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
            eval $(ssh-agent -s)
            echo "${{ secrets.SSH_PRIVATE_KEY }}" | ssh-add -
            mkdir -p ~/.ssh
            echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
            ssh ubuntu@neiron.solutions 'docker-compose down'
            ssh ubuntu@neiron.solutions 'docker-compose up'